services:
  - type: web
    runtime: static
    name: a-ordem-dos-cavaleiros-o-jogo
    repo: https://github.com/washincofer/A-Ordem-dos-Cavaleiros-o-jogo
    branch: main
    buildCommand: bash scripts/render_build.sh
    staticPublishPath: ./build/web
    autoDeployTrigger: commit
    headers:
      - path: /index.html
        name: Cache-Control
        value: no-cache
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
